### ISSUE TITLE
Dependency on baked_file_system commit that no longer exists

### ISSUE THREAD

**Issue by riddley** [hugopl/sidekiq.cr#108]
I was attempting to give this a shot this morning and got this error when running `shards update --ignore-crystal-version`: 

> Could not find commit 7183bfd for shard "baked_file_system" in the repository https://github.com/mperham/baked_file_system.git

**Comment by hugopl** [comment]
but shard.yml get that from `schovi/baked_file_system` not `mperham/baked_file_system`. What version are you trying to build?

**Comment by riddley** [comment]
Sorry I'm fairly new to Crystal and just followed the instructions in the readme. How can I tell?

**Comment by hugopl** [comment]
What version are you trying to build? master branch is pointing to the right repository: https://github.com/mperham/sidekiq.cr/blob/master/shard.yml

**Comment by riddley** [comment]
I think we're recursing.

**Comment by hugopl** [comment]
I don't know what do you plan to do, so the only instructions I can give you is about how to run the examples:
```
git clone git@github.com:mperham/sidekiq.cr.git
cd sidekiq.cr
shards install --ignore-crystal-version
redis-server --logfile /dev/null &
crystal run examples/sidekiq.cr
```
This will create a sidekiq server and a client... the client create 2 jobs that just log `hello` and the server will execute them... in the example there's also 2 middleware (server and client side) that just log stuff.

See https://github.com/mperham/sidekiq.cr/blob/master/examples/sidekiq.cr

**Comment by hugopl** [comment]
Closing this since current version nowadays uses a stable version of `schovi/baked_file_system`.
