### ISSUE TITLE
Web Dashboard

### ISSUE THREAD

**Issue by awcrotwell** [hugopl/sidekiq.cr#85]
Does this Sidekiq version have the ruby/rails dashboard? If so, any documentation on the routes? If not, any plans to add this?

**Comment by mperham** [comment]
Sidekiq.cr is on basic maintenance only. If you want something documented or changed, it’s up to you to send a PR.

**Comment by emq** [comment]
@andrewc910 yes, it does: https://github.com/mperham/sidekiq.cr/wiki/Getting-Started#the-web-ui

**Comment by hugopl** [comment]
Closing this since the question was proper answered.
